const PIG_HEIGHT = 75;
const PIG_WIDTH = PIG_HEIGHT * 14 / 9;

const PIPE_HEIGHT = 500;
const PIPE_WIDTH = 200;
const PIPE_DISTANCE = 700;
const GAP_SIZE = PIG_HEIGHT * 4;

const GAME_HEIGHT = 900;
const GAME_WIDTH = 1600;

const GRAVITY = 90;
const PIG_SPEED = -18;

const SERVER_TICKRATE = 60;
const UPDATE_RATE = 60;
const FRAME_TIME = 1 / SERVER_TICKRATE;
